create table user_info ( first_Name VARCHAR2(50)not null,
                        last_Name VARCHAR2(50)not null,
                        user_Name VARCHAR2(50)primary key  NOT NULL,
                        gender VARCHAR2(10),
                        email_Id VARCHAR2(50) unique,
                        password VARCHAR2(20)not null,
                         mobile_Number NUMBER(12) not null                        
                        );
 
       select * from user_info;
       select * from Company_login;  
       select p.company_id,c.company_name,p.post_id,p.job_title,p.salary,c.location  from posting_job p ,Company_login c
		 		where c.company_id=p.company_id and c.location = 'Kerala';


create table Company_login ( company_id  NUMBER(3)  NOT NULL PRIMARY KEY,
                            company_name varchar2(100)not null,
                            user_name varchar2(100)not null,
                            user_role varchar2(100)not null,
                            phone_number number(10)not null,
                            location varchar2(100)not null,
                            email varchar2(150)unique,
                            password varchar2(20)not null ,
                            register_date date  DEFAULT sysdate);
                                                     
                           select * from Company_login;
                          
create table posting_job ( company_id number(3) ,
                            post_id number(4) GENERATED BY DEFAULT AS IDENTITY (START WITH 1011),
                            job_title varchar2(100)not null,
                            salary int not null,
                            experience varchar2(50)not null,
                            category varchar(100) not null,
                            post_date Date default sysdate,
                            foreign key(company_id)REFERENCES Company_login(company_id));
                            
                          
                            
                                select * from posting_job;
        
create table apply_job( applicant_id  NUMBER(3) GENERATED BY DEFAULT AS IDENTITY (START WITH 201) ,
                        post_id number(4),
                          applicant_name varchar2(100)not null,
                         qualification varchar2(100)not null,
                         skill VARCHAR2(100),
                        age number(2)not null ,
                        email varchar2(150)unique,
                        password varchar2(20)unique not null,
                        address varchar2(200)not null,
                        phone_number number(10)not null,
                        apply_date date  DEFAULT sysdate
                         );
    select * from apply_job;

create table job_status (post_id number(4),
                        applicant_id number(3), 
                        status varchar2(30)
                          );
                        
      select * from job_status;
 
                           commit;
                       
                      
               